os: linux

matrix:
  include:
  - language: ruby
    rvm: 2.2
    before_script:
    - gem install awesome_bot
    script:
    - awesome_bot --allow-redirect --allow-dupe README.md
  - language: python
    python: 3.5
    services:
    - docker
    install:
    - docker build -t rnannot .
    script:
    # run download_sra_metadata.py        
    - docker run --rm rnannot python3 /opt/RNA_repo/rnannot/download_sra_metadata.py -t 1049336 -o TestOutput_1049336.tsv
    # run RNAseq_annotate.py
    - docker run --rm rnannot python3 /opt/RNA_repo/rnannot/RNAseq_annotate.py -i /opt/RNA_repo/example/1049336.tsv -g /opt/RNA_repo/example/Edan07162013.scaffolds.fa.gz -a Edan_2.0 -m 1
  allow_failures:
   - rvm: 2.2

